CREATE TABLE [dbo].[OrderItems]
(
	[BindingId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[OrderId] INT NOT NULL FOREIGN KEY REFERENCES [Orders]([OrderId]),
	[ItemId] INT NOT NULL  FOREIGN KEY REFERENCES [Items]([ItemId]),
)
